"""initial schema

Revision ID: d99e50ceaa8a
Revises: 
Create Date: 2026-08-24 18:55:54.306624
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd99e50ceaa8a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=True),
    sa.Column('intent_id', sa.String(length=64), nullable=True),
    sa.Column('transaction_identity', sa.String(length=96), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_index(op.f('ix_audit_events_id'), 'audit_events', ['id'], unique=True)
    op.create_index(op.f('ix_audit_events_intent_id'), 'audit_events', ['intent_id'], unique=False)
    op.create_index(op.f('ix_audit_events_transaction_id'), 'audit_events', ['transaction_id'], unique=False)
    op.create_table('merchant_orders',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=96), nullable=True),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('total', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_orders_idempotency_key'), 'merchant_orders', ['idempotency_key'], unique=True)
    op.create_table('merchant_products',
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('inventory', sa.Integer(), nullable=False),
    sa.Column('delivery_info', sa.JSON(), nullable=False),
    sa.Column('policy', sa.JSON(), nullable=False),
    sa.Column('force_payment_decline', sa.Boolean(), nullable=False),
    sa.Column('force_order_failure', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('sku')
    )
    op.create_table('mock_payments',
    sa.Column('idempotency_key', sa.String(length=96), nullable=False),
    sa.Column('payment_ref', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('idempotency_key')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('transaction_identity', sa.String(length=96), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('authorized_max_amount', sa.BigInteger(), nullable=True),
    sa.Column('quoted_total', sa.BigInteger(), nullable=True),
    sa.Column('max_quantity', sa.BigInteger(), nullable=True),
    sa.Column('authorized_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('authorizing_intent_id', sa.String(length=64), nullable=True),
    sa.Column('payment_ref', sa.String(length=64), nullable=True),
    sa.Column('merchant_order_id', sa.String(length=64), nullable=True),
    sa.Column('amount_captured', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_transaction_identity'), 'transactions', ['transaction_identity'], unique=True)
    op.create_table('intents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('canonical', sa.JSON(), nullable=False),
    sa.Column('canonical_json', sa.Text(), nullable=False),
    sa.Column('transaction_identity', sa.String(length=96), nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_amount', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intents_transaction_id'), 'intents', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_intents_transaction_identity'), 'intents', ['transaction_identity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intents_transaction_identity'), table_name='intents')
    op.drop_index(op.f('ix_intents_transaction_id'), table_name='intents')
    op.drop_table('intents')
    op.drop_index(op.f('ix_transactions_transaction_identity'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('mock_payments')
    op.drop_table('merchant_products')
    op.drop_index(op.f('ix_merchant_orders_idempotency_key'), table_name='merchant_orders')
    op.drop_table('merchant_orders')
    op.drop_index(op.f('ix_audit_events_transaction_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_intent_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
