"""razorpay linkage

Revision ID: fb42b269fc68
Revises: d99e50ceaa8a
Create Date: 2026-08-24 18:58:14.049654
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fb42b269fc68'
down_revision: str | None = 'd99e50ceaa8a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('razorpay_payments',
    sa.Column('idempotency_key', sa.String(length=96), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_refund_id', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_razorpay_payments_razorpay_order_id'), 'razorpay_payments', ['razorpay_order_id'], unique=True)
    op.add_column('transactions', sa.Column('payment_provider', sa.String(length=16), nullable=True))
    op.add_column('transactions', sa.Column('razorpay_order_id', sa.String(length=64), nullable=True))
    op.add_column('transactions', sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True))
    op.add_column('transactions', sa.Column('razorpay_refund_id', sa.String(length=64), nullable=True))
    op.add_column('transactions', sa.Column('payment_status', sa.String(length=24), nullable=True))
    op.create_index(op.f('ix_transactions_razorpay_order_id'), 'transactions', ['razorpay_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_razorpay_order_id'), table_name='transactions')
    op.drop_column('transactions', 'payment_status')
    op.drop_column('transactions', 'razorpay_refund_id')
    op.drop_column('transactions', 'razorpay_payment_id')
    op.drop_column('transactions', 'razorpay_order_id')
    op.drop_column('transactions', 'payment_provider')
    op.drop_index(op.f('ix_razorpay_payments_razorpay_order_id'), table_name='razorpay_payments')
    op.drop_table('razorpay_payments')
    # ### end Alembic commands ###
